<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="3" time="0.012"><testcase classname="test_sample" name="test_answer" time="0.000520944595337"><failure message="test failure">def test_answer():
&gt;   	assert funcs.increment(3) == 5
E    assert 4 == 5
E     +  where 4 = &lt;function increment at 0x101f02d70&gt;(3)
E     +    where &lt;function increment at 0x101f02d70&gt; = funcs.increment

test_sample.py:5: AssertionError</failure></testcase><testcase classname="test_sample" name="test_answer2" time="9.60826873779e-05"/><testcase classname="test_sample" name="test_answer3" time="9.89437103271e-05"/></testsuite>